// Generated by gencpp from file roboy_communication_cognition/DataQuery.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_DATAQUERY_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_DATAQUERY_H

#include <ros/service_traits.h>


#include <roboy_communication_cognition/DataQueryRequest.h>
#include <roboy_communication_cognition/DataQueryResponse.h>


namespace roboy_communication_cognition
{

struct DataQuery
{

typedef DataQueryRequest Request;
typedef DataQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DataQuery
} // namespace roboy_communication_cognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_cognition::DataQuery > {
  static const char* value()
  {
    return "069affd70d154d413f85fd5c1967eed6";
  }

  static const char* value(const ::roboy_communication_cognition::DataQuery&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_cognition::DataQuery > {
  static const char* value()
  {
    return "roboy_communication_cognition/DataQuery";
  }

  static const char* value(const ::roboy_communication_cognition::DataQuery&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_cognition::DataQueryRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::DataQuery > 
template<>
struct MD5Sum< ::roboy_communication_cognition::DataQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::DataQuery >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DataQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::DataQueryRequest> should match 
// service_traits::DataType< ::roboy_communication_cognition::DataQuery > 
template<>
struct DataType< ::roboy_communication_cognition::DataQueryRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::DataQuery >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DataQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_cognition::DataQueryResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::DataQuery > 
template<>
struct MD5Sum< ::roboy_communication_cognition::DataQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::DataQuery >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DataQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::DataQueryResponse> should match 
// service_traits::DataType< ::roboy_communication_cognition::DataQuery > 
template<>
struct DataType< ::roboy_communication_cognition::DataQueryResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::DataQuery >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DataQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_DATAQUERY_H
