// Generated by gencpp from file roboy_communication_cognition/DetectIntent.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENT_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENT_H

#include <ros/service_traits.h>


#include <roboy_communication_cognition/DetectIntentRequest.h>
#include <roboy_communication_cognition/DetectIntentResponse.h>


namespace roboy_communication_cognition
{

struct DetectIntent
{

typedef DetectIntentRequest Request;
typedef DetectIntentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectIntent
} // namespace roboy_communication_cognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_cognition::DetectIntent > {
  static const char* value()
  {
    return "70b4f9547191039dfd285ee1d326f6c8";
  }

  static const char* value(const ::roboy_communication_cognition::DetectIntent&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_cognition::DetectIntent > {
  static const char* value()
  {
    return "roboy_communication_cognition/DetectIntent";
  }

  static const char* value(const ::roboy_communication_cognition::DetectIntent&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_cognition::DetectIntentRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::DetectIntent > 
template<>
struct MD5Sum< ::roboy_communication_cognition::DetectIntentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::DetectIntent >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DetectIntentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::DetectIntentRequest> should match 
// service_traits::DataType< ::roboy_communication_cognition::DetectIntent > 
template<>
struct DataType< ::roboy_communication_cognition::DetectIntentRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::DetectIntent >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DetectIntentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_cognition::DetectIntentResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::DetectIntent > 
template<>
struct MD5Sum< ::roboy_communication_cognition::DetectIntentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::DetectIntent >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DetectIntentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::DetectIntentResponse> should match 
// service_traits::DataType< ::roboy_communication_cognition::DetectIntent > 
template<>
struct DataType< ::roboy_communication_cognition::DetectIntentResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::DetectIntent >::value();
  }
  static const char* value(const ::roboy_communication_cognition::DetectIntentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENT_H
