// Generated by gencpp from file roboy_communication_cognition/DetectIntentResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENTRESPONSE_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_cognition
{
template <class ContainerAllocator>
struct DetectIntentResponse_
{
  typedef DetectIntentResponse_<ContainerAllocator> Type;

  DetectIntentResponse_()
    : intent()
    , distance(0.0)  {
    }
  DetectIntentResponse_(const ContainerAllocator& _alloc)
    : intent(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intent_type;
  _intent_type intent;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectIntentResponse_

typedef ::roboy_communication_cognition::DetectIntentResponse_<std::allocator<void> > DetectIntentResponse;

typedef boost::shared_ptr< ::roboy_communication_cognition::DetectIntentResponse > DetectIntentResponsePtr;
typedef boost::shared_ptr< ::roboy_communication_cognition::DetectIntentResponse const> DetectIntentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_cognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'roboy_communication_cognition': ['/home/barisyazici/ss18_hand/src/roboy_communication/roboy_communication_cognition/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bc39e7da78ab6f483b19f3968aa3835";
  }

  static const char* value(const ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bc39e7da78ab6f4ULL;
  static const uint64_t static_value2 = 0x83b19f3968aa3835ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_cognition/DetectIntentResponse";
  }

  static const char* value(const ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string intent\n\
float32 distance\n\
";
  }

  static const char* value(const ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intent);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectIntentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_cognition::DetectIntentResponse_<ContainerAllocator>& v)
  {
    s << indent << "intent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intent);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_DETECTINTENTRESPONSE_H
