// Generated by gencpp from file roboy_communication_cognition/LookAtSpeakerResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_LOOKATSPEAKERRESPONSE_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_LOOKATSPEAKERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_cognition
{
template <class ContainerAllocator>
struct LookAtSpeakerResponse_
{
  typedef LookAtSpeakerResponse_<ContainerAllocator> Type;

  LookAtSpeakerResponse_()
    : turned(false)  {
    }
  LookAtSpeakerResponse_(const ContainerAllocator& _alloc)
    : turned(false)  {
  (void)_alloc;
    }



   typedef uint8_t _turned_type;
  _turned_type turned;





  typedef boost::shared_ptr< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LookAtSpeakerResponse_

typedef ::roboy_communication_cognition::LookAtSpeakerResponse_<std::allocator<void> > LookAtSpeakerResponse;

typedef boost::shared_ptr< ::roboy_communication_cognition::LookAtSpeakerResponse > LookAtSpeakerResponsePtr;
typedef boost::shared_ptr< ::roboy_communication_cognition::LookAtSpeakerResponse const> LookAtSpeakerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_cognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roboy_communication_cognition': ['/home/barisyazici/ss18_hand/src/roboy_communication/roboy_communication_cognition/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15a9db50325f4812c0499779cd2dc36e";
  }

  static const char* value(const ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15a9db50325f4812ULL;
  static const uint64_t static_value2 = 0xc0499779cd2dc36eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_cognition/LookAtSpeakerResponse";
  }

  static const char* value(const ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool turned\n\
\n\
";
  }

  static const char* value(const ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LookAtSpeakerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_cognition::LookAtSpeakerResponse_<ContainerAllocator>& v)
  {
    s << indent << "turned: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_LOOKATSPEAKERRESPONSE_H
