// Generated by gencpp from file roboy_communication_cognition/QualityOfTonesRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_QUALITYOFTONESREQUEST_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_QUALITYOFTONESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_cognition
{
template <class ContainerAllocator>
struct QualityOfTonesRequest_
{
  typedef QualityOfTonesRequest_<ContainerAllocator> Type;

  QualityOfTonesRequest_()
    : timeInMilliseconds(0.0)
    , majorOnly(false)  {
    }
  QualityOfTonesRequest_(const ContainerAllocator& _alloc)
    : timeInMilliseconds(0.0)
    , majorOnly(false)  {
  (void)_alloc;
    }



   typedef float _timeInMilliseconds_type;
  _timeInMilliseconds_type timeInMilliseconds;

   typedef uint8_t _majorOnly_type;
  _majorOnly_type majorOnly;





  typedef boost::shared_ptr< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QualityOfTonesRequest_

typedef ::roboy_communication_cognition::QualityOfTonesRequest_<std::allocator<void> > QualityOfTonesRequest;

typedef boost::shared_ptr< ::roboy_communication_cognition::QualityOfTonesRequest > QualityOfTonesRequestPtr;
typedef boost::shared_ptr< ::roboy_communication_cognition::QualityOfTonesRequest const> QualityOfTonesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_cognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roboy_communication_cognition': ['/home/barisyazici/ss18_hand/src/roboy_communication/roboy_communication_cognition/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13a6b42b36123f6f155dd1e0562e1b13";
  }

  static const char* value(const ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13a6b42b36123f6fULL;
  static const uint64_t static_value2 = 0x155dd1e0562e1b13ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_cognition/QualityOfTonesRequest";
  }

  static const char* value(const ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 timeInMilliseconds\n\
bool majorOnly\n\
";
  }

  static const char* value(const ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeInMilliseconds);
      stream.next(m.majorOnly);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QualityOfTonesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_cognition::QualityOfTonesRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeInMilliseconds: ";
    Printer<float>::stream(s, indent + "  ", v.timeInMilliseconds);
    s << indent << "majorOnly: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.majorOnly);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_QUALITYOFTONESREQUEST_H
