// Generated by gencpp from file roboy_communication_cognition/RecognizeObject.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_RECOGNIZEOBJECT_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_RECOGNIZEOBJECT_H

#include <ros/service_traits.h>


#include <roboy_communication_cognition/RecognizeObjectRequest.h>
#include <roboy_communication_cognition/RecognizeObjectResponse.h>


namespace roboy_communication_cognition
{

struct RecognizeObject
{

typedef RecognizeObjectRequest Request;
typedef RecognizeObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecognizeObject
} // namespace roboy_communication_cognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_cognition::RecognizeObject > {
  static const char* value()
  {
    return "258a9296e168e47170c83d2bf19a1ae6";
  }

  static const char* value(const ::roboy_communication_cognition::RecognizeObject&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_cognition::RecognizeObject > {
  static const char* value()
  {
    return "roboy_communication_cognition/RecognizeObject";
  }

  static const char* value(const ::roboy_communication_cognition::RecognizeObject&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_cognition::RecognizeObjectRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::RecognizeObject > 
template<>
struct MD5Sum< ::roboy_communication_cognition::RecognizeObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::RecognizeObject >::value();
  }
  static const char* value(const ::roboy_communication_cognition::RecognizeObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::RecognizeObjectRequest> should match 
// service_traits::DataType< ::roboy_communication_cognition::RecognizeObject > 
template<>
struct DataType< ::roboy_communication_cognition::RecognizeObjectRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::RecognizeObject >::value();
  }
  static const char* value(const ::roboy_communication_cognition::RecognizeObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_cognition::RecognizeObjectResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::RecognizeObject > 
template<>
struct MD5Sum< ::roboy_communication_cognition::RecognizeObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::RecognizeObject >::value();
  }
  static const char* value(const ::roboy_communication_cognition::RecognizeObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::RecognizeObjectResponse> should match 
// service_traits::DataType< ::roboy_communication_cognition::RecognizeObject > 
template<>
struct DataType< ::roboy_communication_cognition::RecognizeObjectResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::RecognizeObject >::value();
  }
  static const char* value(const ::roboy_communication_cognition::RecognizeObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_RECOGNIZEOBJECT_H
