// Generated by gencpp from file roboy_communication_cognition/ShowInstances.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCES_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCES_H

#include <ros/service_traits.h>


#include <roboy_communication_cognition/ShowInstancesRequest.h>
#include <roboy_communication_cognition/ShowInstancesResponse.h>


namespace roboy_communication_cognition
{

struct ShowInstances
{

typedef ShowInstancesRequest Request;
typedef ShowInstancesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShowInstances
} // namespace roboy_communication_cognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_cognition::ShowInstances > {
  static const char* value()
  {
    return "cdb5eab71cb46cce11dc358585f13c8e";
  }

  static const char* value(const ::roboy_communication_cognition::ShowInstances&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_cognition::ShowInstances > {
  static const char* value()
  {
    return "roboy_communication_cognition/ShowInstances";
  }

  static const char* value(const ::roboy_communication_cognition::ShowInstances&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_cognition::ShowInstancesRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::ShowInstances > 
template<>
struct MD5Sum< ::roboy_communication_cognition::ShowInstancesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::ShowInstances >::value();
  }
  static const char* value(const ::roboy_communication_cognition::ShowInstancesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::ShowInstancesRequest> should match 
// service_traits::DataType< ::roboy_communication_cognition::ShowInstances > 
template<>
struct DataType< ::roboy_communication_cognition::ShowInstancesRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::ShowInstances >::value();
  }
  static const char* value(const ::roboy_communication_cognition::ShowInstancesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_cognition::ShowInstancesResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_cognition::ShowInstances > 
template<>
struct MD5Sum< ::roboy_communication_cognition::ShowInstancesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_cognition::ShowInstances >::value();
  }
  static const char* value(const ::roboy_communication_cognition::ShowInstancesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_cognition::ShowInstancesResponse> should match 
// service_traits::DataType< ::roboy_communication_cognition::ShowInstances > 
template<>
struct DataType< ::roboy_communication_cognition::ShowInstancesResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_cognition::ShowInstances >::value();
  }
  static const char* value(const ::roboy_communication_cognition::ShowInstancesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCES_H
