// Generated by gencpp from file roboy_communication_cognition/ShowInstancesResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCESRESPONSE_H
#define ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_cognition
{
template <class ContainerAllocator>
struct ShowInstancesResponse_
{
  typedef ShowInstancesResponse_<ContainerAllocator> Type;

  ShowInstancesResponse_()
    : instances()  {
    }
  ShowInstancesResponse_(const ContainerAllocator& _alloc)
    : instances(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _instances_type;
  _instances_type instances;





  typedef boost::shared_ptr< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ShowInstancesResponse_

typedef ::roboy_communication_cognition::ShowInstancesResponse_<std::allocator<void> > ShowInstancesResponse;

typedef boost::shared_ptr< ::roboy_communication_cognition::ShowInstancesResponse > ShowInstancesResponsePtr;
typedef boost::shared_ptr< ::roboy_communication_cognition::ShowInstancesResponse const> ShowInstancesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_cognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'roboy_communication_cognition': ['/home/barisyazici/ss18_hand/src/roboy_communication/roboy_communication_cognition/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c37cf4d14d6c5bfa6fbe319c1865eb5a";
  }

  static const char* value(const ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc37cf4d14d6c5bfaULL;
  static const uint64_t static_value2 = 0x6fbe319c1865eb5aULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_cognition/ShowInstancesResponse";
  }

  static const char* value(const ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] instances\n\
\n\
";
  }

  static const char* value(const ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.instances);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShowInstancesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_cognition::ShowInstancesResponse_<ContainerAllocator>& v)
  {
    s << indent << "instances[]" << std::endl;
    for (size_t i = 0; i < v.instances.size(); ++i)
    {
      s << indent << "  instances[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.instances[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_COGNITION_MESSAGE_SHOWINSTANCESRESPONSE_H
