(cl:in-package roboy_communication_simulation-msg)
(cl:export '(ROBOYID-VAL
          ROBOYID
          F_CONTACT-VAL
          F_CONTACT
          D_LIFT-VAL
          D_LIFT
          D_PREP-VAL
          D_PREP
          F_MAX-VAL
          F_MAX
          PSI_HEADING-VAL
          PSI_HEADING
          OMEGA_HEADING-VAL
          OMEGA_HEADING
          V_FORWARD-VAL
          V_FORWARD
          V_COM-VAL
          V_COM
          K_V-VAL
          K_V
          K_H-VAL
          K_H
          K_P_THETA_LEFT-VAL
          K_P_THETA_LEFT
          K_P_THETA_RIGHT-VAL
          K_P_THETA_RIGHT
          K_D_THETA_LEFT-VAL
          K_D_THETA_LEFT
          K_D_THETA_RIGHT-VAL
          K_D_THETA_RIGHT
          K_P_PHI-VAL
          K_P_PHI
          K_D_PHI-VAL
          K_D_PHI
          K_V-VAL
          K_V
          K_P-VAL
          K_P
          K_Q-VAL
          K_Q
          K_OMEGA-VAL
          K_OMEGA
          K_M_FPLUS-VAL
          K_M_FPLUS
          C_HIP_LIFT-VAL
          C_HIP_LIFT
          C_KNEE_LIFT-VAL
          C_KNEE_LIFT
          C_STANCE_LIFT-VAL
          C_STANCE_LIFT
          C_SWING_PREP-VAL
          C_SWING_PREP
          THETA_GROIN_0-VAL
          THETA_GROIN_0
          PHI_GROIN_0-VAL
          PHI_GROIN_0
          THETA_TRUNK_0-VAL
          THETA_TRUNK_0
          PHI_TRUNK_0-VAL
          PHI_TRUNK_0
          THETA_KNEE-VAL
          THETA_KNEE
          THETA_ANKLE-VAL
          THETA_ANKLE
          D_S-VAL
          D_S
          D_C-VAL
          D_C
          V_S-VAL
          V_S
          V_C-VAL
          V_C
          SIM_TIME-VAL
          SIM_TIME
))