# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_communication_simulation/ControllerParameters.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControllerParameters(genpy.Message):
  _md5sum = "8d876cb1f4a80d09d45e86f5cbdeda08"
  _type = "roboy_communication_simulation/ControllerParameters"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 roboyID
float64 F_contact
float64 d_lift
float64 d_prep
float64 F_max
float64 psi_heading
float64 omega_heading
float64 v_forward
float64 v_COM
float64 k_v
float64 k_h
float64[] k_p_theta_left
float64[] k_p_theta_right
float64[] k_d_theta_left
float64[] k_d_theta_right
float64[] k_p_phi
float64[] k_d_phi
float64 k_V
float64 k_P
float64 k_Q
float64 k_omega
float64 k_M_Fplus
float64 c_hip_lift
float64 c_knee_lift
float64 c_stance_lift
float64 c_swing_prep
float64[] theta_groin_0
float64[] phi_groin_0
float64 theta_trunk_0
float64 phi_trunk_0
float64[] theta_knee
float64[] theta_ankle
float64[] d_s
float64[] d_c
float64[] v_s
float64[] v_c
float32 sim_time"""
  __slots__ = ['roboyID','F_contact','d_lift','d_prep','F_max','psi_heading','omega_heading','v_forward','v_COM','k_v','k_h','k_p_theta_left','k_p_theta_right','k_d_theta_left','k_d_theta_right','k_p_phi','k_d_phi','k_V','k_P','k_Q','k_omega','k_M_Fplus','c_hip_lift','c_knee_lift','c_stance_lift','c_swing_prep','theta_groin_0','phi_groin_0','theta_trunk_0','phi_trunk_0','theta_knee','theta_ankle','d_s','d_c','v_s','v_c','sim_time']
  _slot_types = ['int32','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64[]','float64[]','float64','float64','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roboyID,F_contact,d_lift,d_prep,F_max,psi_heading,omega_heading,v_forward,v_COM,k_v,k_h,k_p_theta_left,k_p_theta_right,k_d_theta_left,k_d_theta_right,k_p_phi,k_d_phi,k_V,k_P,k_Q,k_omega,k_M_Fplus,c_hip_lift,c_knee_lift,c_stance_lift,c_swing_prep,theta_groin_0,phi_groin_0,theta_trunk_0,phi_trunk_0,theta_knee,theta_ankle,d_s,d_c,v_s,v_c,sim_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerParameters, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.roboyID is None:
        self.roboyID = 0
      if self.F_contact is None:
        self.F_contact = 0.
      if self.d_lift is None:
        self.d_lift = 0.
      if self.d_prep is None:
        self.d_prep = 0.
      if self.F_max is None:
        self.F_max = 0.
      if self.psi_heading is None:
        self.psi_heading = 0.
      if self.omega_heading is None:
        self.omega_heading = 0.
      if self.v_forward is None:
        self.v_forward = 0.
      if self.v_COM is None:
        self.v_COM = 0.
      if self.k_v is None:
        self.k_v = 0.
      if self.k_h is None:
        self.k_h = 0.
      if self.k_p_theta_left is None:
        self.k_p_theta_left = []
      if self.k_p_theta_right is None:
        self.k_p_theta_right = []
      if self.k_d_theta_left is None:
        self.k_d_theta_left = []
      if self.k_d_theta_right is None:
        self.k_d_theta_right = []
      if self.k_p_phi is None:
        self.k_p_phi = []
      if self.k_d_phi is None:
        self.k_d_phi = []
      if self.k_V is None:
        self.k_V = 0.
      if self.k_P is None:
        self.k_P = 0.
      if self.k_Q is None:
        self.k_Q = 0.
      if self.k_omega is None:
        self.k_omega = 0.
      if self.k_M_Fplus is None:
        self.k_M_Fplus = 0.
      if self.c_hip_lift is None:
        self.c_hip_lift = 0.
      if self.c_knee_lift is None:
        self.c_knee_lift = 0.
      if self.c_stance_lift is None:
        self.c_stance_lift = 0.
      if self.c_swing_prep is None:
        self.c_swing_prep = 0.
      if self.theta_groin_0 is None:
        self.theta_groin_0 = []
      if self.phi_groin_0 is None:
        self.phi_groin_0 = []
      if self.theta_trunk_0 is None:
        self.theta_trunk_0 = 0.
      if self.phi_trunk_0 is None:
        self.phi_trunk_0 = 0.
      if self.theta_knee is None:
        self.theta_knee = []
      if self.theta_ankle is None:
        self.theta_ankle = []
      if self.d_s is None:
        self.d_s = []
      if self.d_c is None:
        self.d_c = []
      if self.v_s is None:
        self.v_s = []
      if self.v_c is None:
        self.v_c = []
      if self.sim_time is None:
        self.sim_time = 0.
    else:
      self.roboyID = 0
      self.F_contact = 0.
      self.d_lift = 0.
      self.d_prep = 0.
      self.F_max = 0.
      self.psi_heading = 0.
      self.omega_heading = 0.
      self.v_forward = 0.
      self.v_COM = 0.
      self.k_v = 0.
      self.k_h = 0.
      self.k_p_theta_left = []
      self.k_p_theta_right = []
      self.k_d_theta_left = []
      self.k_d_theta_right = []
      self.k_p_phi = []
      self.k_d_phi = []
      self.k_V = 0.
      self.k_P = 0.
      self.k_Q = 0.
      self.k_omega = 0.
      self.k_M_Fplus = 0.
      self.c_hip_lift = 0.
      self.c_knee_lift = 0.
      self.c_stance_lift = 0.
      self.c_swing_prep = 0.
      self.theta_groin_0 = []
      self.phi_groin_0 = []
      self.theta_trunk_0 = 0.
      self.phi_trunk_0 = 0.
      self.theta_knee = []
      self.theta_ankle = []
      self.d_s = []
      self.d_c = []
      self.v_s = []
      self.v_c = []
      self.sim_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i10d().pack(_x.roboyID, _x.F_contact, _x.d_lift, _x.d_prep, _x.F_max, _x.psi_heading, _x.omega_heading, _x.v_forward, _x.v_COM, _x.k_v, _x.k_h))
      length = len(self.k_p_theta_left)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_p_theta_left))
      length = len(self.k_p_theta_right)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_p_theta_right))
      length = len(self.k_d_theta_left)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_d_theta_left))
      length = len(self.k_d_theta_right)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_d_theta_right))
      length = len(self.k_p_phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_p_phi))
      length = len(self.k_d_phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.k_d_phi))
      _x = self
      buff.write(_get_struct_9d().pack(_x.k_V, _x.k_P, _x.k_Q, _x.k_omega, _x.k_M_Fplus, _x.c_hip_lift, _x.c_knee_lift, _x.c_stance_lift, _x.c_swing_prep))
      length = len(self.theta_groin_0)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.theta_groin_0))
      length = len(self.phi_groin_0)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.phi_groin_0))
      _x = self
      buff.write(_get_struct_2d().pack(_x.theta_trunk_0, _x.phi_trunk_0))
      length = len(self.theta_knee)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.theta_knee))
      length = len(self.theta_ankle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.theta_ankle))
      length = len(self.d_s)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.d_s))
      length = len(self.d_c)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.d_c))
      length = len(self.v_s)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.v_s))
      length = len(self.v_c)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.v_c))
      buff.write(_get_struct_f().pack(self.sim_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.roboyID, _x.F_contact, _x.d_lift, _x.d_prep, _x.F_max, _x.psi_heading, _x.omega_heading, _x.v_forward, _x.v_COM, _x.k_v, _x.k_h,) = _get_struct_i10d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_theta_left = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_theta_right = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_theta_left = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_theta_right = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_phi = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_phi = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 72
      (_x.k_V, _x.k_P, _x.k_Q, _x.k_omega, _x.k_M_Fplus, _x.c_hip_lift, _x.c_knee_lift, _x.c_stance_lift, _x.c_swing_prep,) = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_groin_0 = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.phi_groin_0 = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 16
      (_x.theta_trunk_0, _x.phi_trunk_0,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_knee = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_ankle = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.d_s = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.d_c = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.v_s = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.v_c = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (self.sim_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i10d().pack(_x.roboyID, _x.F_contact, _x.d_lift, _x.d_prep, _x.F_max, _x.psi_heading, _x.omega_heading, _x.v_forward, _x.v_COM, _x.k_v, _x.k_h))
      length = len(self.k_p_theta_left)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_p_theta_left.tostring())
      length = len(self.k_p_theta_right)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_p_theta_right.tostring())
      length = len(self.k_d_theta_left)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_d_theta_left.tostring())
      length = len(self.k_d_theta_right)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_d_theta_right.tostring())
      length = len(self.k_p_phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_p_phi.tostring())
      length = len(self.k_d_phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.k_d_phi.tostring())
      _x = self
      buff.write(_get_struct_9d().pack(_x.k_V, _x.k_P, _x.k_Q, _x.k_omega, _x.k_M_Fplus, _x.c_hip_lift, _x.c_knee_lift, _x.c_stance_lift, _x.c_swing_prep))
      length = len(self.theta_groin_0)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.theta_groin_0.tostring())
      length = len(self.phi_groin_0)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.phi_groin_0.tostring())
      _x = self
      buff.write(_get_struct_2d().pack(_x.theta_trunk_0, _x.phi_trunk_0))
      length = len(self.theta_knee)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.theta_knee.tostring())
      length = len(self.theta_ankle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.theta_ankle.tostring())
      length = len(self.d_s)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.d_s.tostring())
      length = len(self.d_c)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.d_c.tostring())
      length = len(self.v_s)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.v_s.tostring())
      length = len(self.v_c)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.v_c.tostring())
      buff.write(_get_struct_f().pack(self.sim_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.roboyID, _x.F_contact, _x.d_lift, _x.d_prep, _x.F_max, _x.psi_heading, _x.omega_heading, _x.v_forward, _x.v_COM, _x.k_v, _x.k_h,) = _get_struct_i10d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_theta_left = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_theta_right = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_theta_left = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_theta_right = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_p_phi = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.k_d_phi = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 72
      (_x.k_V, _x.k_P, _x.k_Q, _x.k_omega, _x.k_M_Fplus, _x.c_hip_lift, _x.c_knee_lift, _x.c_stance_lift, _x.c_swing_prep,) = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_groin_0 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.phi_groin_0 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 16
      (_x.theta_trunk_0, _x.phi_trunk_0,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_knee = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.theta_ankle = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.d_s = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.d_c = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.v_s = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.v_c = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (self.sim_time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_i10d = None
def _get_struct_i10d():
    global _struct_i10d
    if _struct_i10d is None:
        _struct_i10d = struct.Struct("<i10d")
    return _struct_i10d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
