# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_communication_simulation/RecordingControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RecordingControl(genpy.Message):
  _md5sum = "a1f619fdc44f7b747ba8736a6b246929"
  _type = "roboy_communication_simulation/RecordingControl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 roboyID
uint32 start_time
uint32 stop_time
"""
  __slots__ = ['roboyID','start_time','stop_time']
  _slot_types = ['int32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roboyID,start_time,stop_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RecordingControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.roboyID is None:
        self.roboyID = 0
      if self.start_time is None:
        self.start_time = 0
      if self.stop_time is None:
        self.stop_time = 0
    else:
      self.roboyID = 0
      self.start_time = 0
      self.stop_time = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2I().pack(_x.roboyID, _x.start_time, _x.stop_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.roboyID, _x.start_time, _x.stop_time,) = _get_struct_i2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2I().pack(_x.roboyID, _x.start_time, _x.stop_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.roboyID, _x.start_time, _x.stop_time,) = _get_struct_i2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2I = None
def _get_struct_i2I():
    global _struct_i2I
    if _struct_i2I is None:
        _struct_i2I = struct.Struct("<i2I")
    return _struct_i2I
