# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_communication_cognition/QualityOfToneRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class QualityOfToneRequest(genpy.Message):
  _md5sum = "24bc5808ec6c93933487ee2461a3492b"
  _type = "roboy_communication_cognition/QualityOfToneRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string tone
float32 timeInMilliseconds
bool majorOnly
"""
  __slots__ = ['tone','timeInMilliseconds','majorOnly']
  _slot_types = ['string','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tone,timeInMilliseconds,majorOnly

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(QualityOfToneRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.tone is None:
        self.tone = ''
      if self.timeInMilliseconds is None:
        self.timeInMilliseconds = 0.
      if self.majorOnly is None:
        self.majorOnly = False
    else:
      self.tone = ''
      self.timeInMilliseconds = 0.
      self.majorOnly = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.tone
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fB().pack(_x.timeInMilliseconds, _x.majorOnly))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tone = str[start:end].decode('utf-8')
      else:
        self.tone = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.timeInMilliseconds, _x.majorOnly,) = _get_struct_fB().unpack(str[start:end])
      self.majorOnly = bool(self.majorOnly)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.tone
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fB().pack(_x.timeInMilliseconds, _x.majorOnly))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tone = str[start:end].decode('utf-8')
      else:
        self.tone = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.timeInMilliseconds, _x.majorOnly,) = _get_struct_fB().unpack(str[start:end])
      self.majorOnly = bool(self.majorOnly)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fB = None
def _get_struct_fB():
    global _struct_fB
    if _struct_fB is None:
        _struct_fB = struct.Struct("<fB")
    return _struct_fB
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_communication_cognition/QualityOfToneResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class QualityOfToneResponse(genpy.Message):
  _md5sum = "c3ecd484b1871a72a048f022c3cda1d2"
  _type = "roboy_communication_cognition/QualityOfToneResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 quality
float32 purity
float32 directionZ
float32 directionY
bool hitPin

"""
  __slots__ = ['quality','purity','directionZ','directionY','hitPin']
  _slot_types = ['float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       quality,purity,directionZ,directionY,hitPin

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(QualityOfToneResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.quality is None:
        self.quality = 0.
      if self.purity is None:
        self.purity = 0.
      if self.directionZ is None:
        self.directionZ = 0.
      if self.directionY is None:
        self.directionY = 0.
      if self.hitPin is None:
        self.hitPin = False
    else:
      self.quality = 0.
      self.purity = 0.
      self.directionZ = 0.
      self.directionY = 0.
      self.hitPin = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4fB().pack(_x.quality, _x.purity, _x.directionZ, _x.directionY, _x.hitPin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.quality, _x.purity, _x.directionZ, _x.directionY, _x.hitPin,) = _get_struct_4fB().unpack(str[start:end])
      self.hitPin = bool(self.hitPin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4fB().pack(_x.quality, _x.purity, _x.directionZ, _x.directionY, _x.hitPin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.quality, _x.purity, _x.directionZ, _x.directionY, _x.hitPin,) = _get_struct_4fB().unpack(str[start:end])
      self.hitPin = bool(self.hitPin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4fB = None
def _get_struct_4fB():
    global _struct_4fB
    if _struct_4fB is None:
        _struct_4fB = struct.Struct("<4fB")
    return _struct_4fB
class QualityOfTone(object):
  _type          = 'roboy_communication_cognition/QualityOfTone'
  _md5sum = 'ebc7c4e9f07e3e393dc5857ee7083482'
  _request_class  = QualityOfToneRequest
  _response_class = QualityOfToneResponse
