(cl:defpackage roboy_communication_simulation-srv
  (:use )
  (:export
   "ENERGIES"
   "<ENERGIES-REQUEST>"
   "ENERGIES-REQUEST"
   "<ENERGIES-RESPONSE>"
   "ENERGIES-RESPONSE"
   "UPDATECONTROLLERPARAMETERS"
   "<UPDATECONTROLLERPARAMETERS-REQUEST>"
   "UPDATECONTROLLERPARAMETERS-REQUEST"
   "<UPDATECONTROLLERPARAMETERS-RESPONSE>"
   "UPDATECONTROLLERPARAMETERS-RESPONSE"
  ))

