// Generated by gencpp from file roboy_communication_simulation/LegState.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_SIMULATION_MESSAGE_LEGSTATE_H
#define ROBOY_COMMUNICATION_SIMULATION_MESSAGE_LEGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_simulation
{
template <class ContainerAllocator>
struct LegState_
{
  typedef LegState_<ContainerAllocator> Type;

  LegState_()
    : roboyID(0)
    , leg(0)
    , state(0)  {
    }
  LegState_(const ContainerAllocator& _alloc)
    : roboyID(0)
    , leg(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int32_t _roboyID_type;
  _roboyID_type roboyID;

   typedef int32_t _leg_type;
  _leg_type leg;

   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::roboy_communication_simulation::LegState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_simulation::LegState_<ContainerAllocator> const> ConstPtr;

}; // struct LegState_

typedef ::roboy_communication_simulation::LegState_<std::allocator<void> > LegState;

typedef boost::shared_ptr< ::roboy_communication_simulation::LegState > LegStatePtr;
typedef boost::shared_ptr< ::roboy_communication_simulation::LegState const> LegStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_simulation::LegState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_simulation::LegState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roboy_communication_simulation': ['/home/barisyazici/ss18_hand/src/roboy_communication/simulation/msgs'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_simulation::LegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_simulation::LegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_simulation::LegState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3dd49eede2d5daac3acf9a5bd32dc15";
  }

  static const char* value(const ::roboy_communication_simulation::LegState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3dd49eede2d5daaULL;
  static const uint64_t static_value2 = 0xc3acf9a5bd32dc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_simulation/LegState";
  }

  static const char* value(const ::roboy_communication_simulation::LegState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 roboyID\n\
int32 leg\n\
int32 state\n\
";
  }

  static const char* value(const ::roboy_communication_simulation::LegState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roboyID);
      stream.next(m.leg);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_simulation::LegState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_simulation::LegState_<ContainerAllocator>& v)
  {
    s << indent << "roboyID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roboyID);
    s << indent << "leg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leg);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_SIMULATION_MESSAGE_LEGSTATE_H
