// Generated by gencpp from file roboy_communication_middleware/DanceTrajectory.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DANCETRAJECTORY_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DANCETRAJECTORY_H

#include <ros/service_traits.h>


#include <roboy_communication_middleware/DanceTrajectoryRequest.h>
#include <roboy_communication_middleware/DanceTrajectoryResponse.h>


namespace roboy_communication_middleware
{

struct DanceTrajectory
{

typedef DanceTrajectoryRequest Request;
typedef DanceTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DanceTrajectory
} // namespace roboy_communication_middleware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_middleware::DanceTrajectory > {
  static const char* value()
  {
    return "c1811518113b89edafd5bab82a308c0b";
  }

  static const char* value(const ::roboy_communication_middleware::DanceTrajectory&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_middleware::DanceTrajectory > {
  static const char* value()
  {
    return "roboy_communication_middleware/DanceTrajectory";
  }

  static const char* value(const ::roboy_communication_middleware::DanceTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_middleware::DanceTrajectoryRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_middleware::DanceTrajectory > 
template<>
struct MD5Sum< ::roboy_communication_middleware::DanceTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_middleware::DanceTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::DanceTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_middleware::DanceTrajectoryRequest> should match 
// service_traits::DataType< ::roboy_communication_middleware::DanceTrajectory > 
template<>
struct DataType< ::roboy_communication_middleware::DanceTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_middleware::DanceTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::DanceTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_middleware::DanceTrajectoryResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_middleware::DanceTrajectory > 
template<>
struct MD5Sum< ::roboy_communication_middleware::DanceTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_middleware::DanceTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::DanceTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_middleware::DanceTrajectoryResponse> should match 
// service_traits::DataType< ::roboy_communication_middleware::DanceTrajectory > 
template<>
struct DataType< ::roboy_communication_middleware::DanceTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_middleware::DanceTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::DanceTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DANCETRAJECTORY_H
