// Generated by gencpp from file roboy_communication_middleware/DarkRoomStatistics.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOMSTATISTICS_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOMSTATISTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct DarkRoomStatistics_
{
  typedef DarkRoomStatistics_<ContainerAllocator> Type;

  DarkRoomStatistics_()
    : object_name()
    , lighthouse(0)
    , updateFrequency_horizontal()
    , updateFrequency_vertical()  {
    }
  DarkRoomStatistics_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , lighthouse(0)
    , updateFrequency_horizontal(_alloc)
    , updateFrequency_vertical(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef int32_t _lighthouse_type;
  _lighthouse_type lighthouse;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _updateFrequency_horizontal_type;
  _updateFrequency_horizontal_type updateFrequency_horizontal;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _updateFrequency_vertical_type;
  _updateFrequency_vertical_type updateFrequency_vertical;





  typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> const> ConstPtr;

}; // struct DarkRoomStatistics_

typedef ::roboy_communication_middleware::DarkRoomStatistics_<std::allocator<void> > DarkRoomStatistics;

typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoomStatistics > DarkRoomStatisticsPtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoomStatistics const> DarkRoomStatisticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/barisyazici/ss18_hand/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7aa7daab9e7ff8fdfb2e001f35611191";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7aa7daab9e7ff8fdULL;
  static const uint64_t static_value2 = 0xfb2e001f35611191ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/DarkRoomStatistics";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n\
int32 lighthouse\n\
float32[] updateFrequency_horizontal\n\
float32[] updateFrequency_vertical\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.lighthouse);
      stream.next(m.updateFrequency_horizontal);
      stream.next(m.updateFrequency_vertical);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DarkRoomStatistics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::DarkRoomStatistics_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "lighthouse: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lighthouse);
    s << indent << "updateFrequency_horizontal[]" << std::endl;
    for (size_t i = 0; i < v.updateFrequency_horizontal.size(); ++i)
    {
      s << indent << "  updateFrequency_horizontal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.updateFrequency_horizontal[i]);
    }
    s << indent << "updateFrequency_vertical[]" << std::endl;
    for (size_t i = 0; i < v.updateFrequency_vertical.size(); ++i)
    {
      s << indent << "  updateFrequency_vertical[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.updateFrequency_vertical[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOMSTATISTICS_H
