// Generated by gencpp from file roboy_communication_middleware/HandCommand.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_HANDCOMMAND_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_HANDCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct HandCommand_
{
  typedef HandCommand_<ContainerAllocator> Type;

  HandCommand_()
    : id(0)
    , setPoint()
    , motorid()  {
    }
  HandCommand_(const ContainerAllocator& _alloc)
    : id(0)
    , setPoint(_alloc)
    , motorid(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _setPoint_type;
  _setPoint_type setPoint;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _motorid_type;
  _motorid_type motorid;





  typedef boost::shared_ptr< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HandCommand_

typedef ::roboy_communication_middleware::HandCommand_<std::allocator<void> > HandCommand;

typedef boost::shared_ptr< ::roboy_communication_middleware::HandCommand > HandCommandPtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::HandCommand const> HandCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::HandCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/barisyazici/ss18_hand/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33ffaf8168256fe4b3d8ba74b9a0642d";
  }

  static const char* value(const ::roboy_communication_middleware::HandCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33ffaf8168256fe4ULL;
  static const uint64_t static_value2 = 0xb3d8ba74b9a0642dULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/HandCommand";
  }

  static const char* value(const ::roboy_communication_middleware::HandCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8[] setPoint\n\
uint8[] motorid\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::HandCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.setPoint);
      stream.next(m.motorid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::HandCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::HandCommand_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "setPoint[]" << std::endl;
    for (size_t i = 0; i < v.setPoint.size(); ++i)
    {
      s << indent << "  setPoint[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.setPoint[i]);
    }
    s << indent << "motorid[]" << std::endl;
    for (size_t i = 0; i < v.motorid.size(); ++i)
    {
      s << indent << "  motorid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.motorid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_HANDCOMMAND_H
