// Generated by gencpp from file roboy_communication_middleware/InitializeRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_INITIALIZEREQUEST_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_INITIALIZEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct InitializeRequest_
{
  typedef InitializeRequest_<ContainerAllocator> Type;

  InitializeRequest_()
    : idList()
    , controlmode()  {
    }
  InitializeRequest_(const ContainerAllocator& _alloc)
    : idList(_alloc)
    , controlmode(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _idList_type;
  _idList_type idList;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _controlmode_type;
  _controlmode_type controlmode;





  typedef boost::shared_ptr< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitializeRequest_

typedef ::roboy_communication_middleware::InitializeRequest_<std::allocator<void> > InitializeRequest;

typedef boost::shared_ptr< ::roboy_communication_middleware::InitializeRequest > InitializeRequestPtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::InitializeRequest const> InitializeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/barisyazici/ss18_hand/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0591953f6b567fe9ce7cfe32b66c94e";
  }

  static const char* value(const ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0591953f6b567feULL;
  static const uint64_t static_value2 = 0x9ce7cfe32b66c94eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/InitializeRequest";
  }

  static const char* value(const ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] idList\n\
uint8[] controlmode\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idList);
      stream.next(m.controlmode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::InitializeRequest_<ContainerAllocator>& v)
  {
    s << indent << "idList[]" << std::endl;
    for (size_t i = 0; i < v.idList.size(); ++i)
    {
      s << indent << "  idList[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.idList[i]);
    }
    s << indent << "controlmode[]" << std::endl;
    for (size_t i = 0; i < v.controlmode.size(); ++i)
    {
      s << indent << "  controlmode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.controlmode[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_INITIALIZEREQUEST_H
