// Generated by gencpp from file roboy_communication_middleware/MotorConfigServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCONFIGSERVICERESPONSE_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCONFIGSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct MotorConfigServiceResponse_
{
  typedef MotorConfigServiceResponse_<ContainerAllocator> Type;

  MotorConfigServiceResponse_()
    : mode()  {
    }
  MotorConfigServiceResponse_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorConfigServiceResponse_

typedef ::roboy_communication_middleware::MotorConfigServiceResponse_<std::allocator<void> > MotorConfigServiceResponse;

typedef boost::shared_ptr< ::roboy_communication_middleware::MotorConfigServiceResponse > MotorConfigServiceResponsePtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::MotorConfigServiceResponse const> MotorConfigServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/barisyazici/ss18_hand/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fd7890fd399a8964959d3d06ecb53b5";
  }

  static const char* value(const ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fd7890fd399a896ULL;
  static const uint64_t static_value2 = 0x4959d3d06ecb53b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/MotorConfigServiceResponse";
  }

  static const char* value(const ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] mode\n\
\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorConfigServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::MotorConfigServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "mode[]" << std::endl;
    for (size_t i = 0; i < v.mode.size(); ++i)
    {
      s << indent << "  mode[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.mode[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCONFIGSERVICERESPONSE_H
