// Generated by gencpp from file roboy_communication_middleware/MotorCalibrationServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct MotorCalibrationServiceResponse_
{
  typedef MotorCalibrationServiceResponse_<ContainerAllocator> Type;

  MotorCalibrationServiceResponse_()
    : estimated_spring_parameters()
    , load()
    , displacement()  {
    }
  MotorCalibrationServiceResponse_(const ContainerAllocator& _alloc)
    : estimated_spring_parameters(_alloc)
    , load(_alloc)
    , displacement(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _estimated_spring_parameters_type;
  _estimated_spring_parameters_type estimated_spring_parameters;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _load_type;
  _load_type load;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _displacement_type;
  _displacement_type displacement;





  typedef boost::shared_ptr< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCalibrationServiceResponse_

typedef ::roboy_communication_middleware::MotorCalibrationServiceResponse_<std::allocator<void> > MotorCalibrationServiceResponse;

typedef boost::shared_ptr< ::roboy_communication_middleware::MotorCalibrationServiceResponse > MotorCalibrationServiceResponsePtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::MotorCalibrationServiceResponse const> MotorCalibrationServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/barisyazici/ss18_hand/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbaac264566b037dc730e8ef15ebdc8f";
  }

  static const char* value(const ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbaac264566b037dULL;
  static const uint64_t static_value2 = 0xc730e8ef15ebdc8fULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/MotorCalibrationServiceResponse";
  }

  static const char* value(const ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] estimated_spring_parameters\n\
float64[] load\n\
float64[] displacement\n\
\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estimated_spring_parameters);
      stream.next(m.load);
      stream.next(m.displacement);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCalibrationServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::MotorCalibrationServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "estimated_spring_parameters[]" << std::endl;
    for (size_t i = 0; i < v.estimated_spring_parameters.size(); ++i)
    {
      s << indent << "  estimated_spring_parameters[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.estimated_spring_parameters[i]);
    }
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.load[i]);
    }
    s << indent << "displacement[]" << std::endl;
    for (size_t i = 0; i < v.displacement.size(); ++i)
    {
      s << indent << "  displacement[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.displacement[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H
