// Generated by gencpp from file roboy_communication_middleware/SetTrajectory.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_SETTRAJECTORY_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_SETTRAJECTORY_H

#include <ros/service_traits.h>


#include <roboy_communication_middleware/SetTrajectoryRequest.h>
#include <roboy_communication_middleware/SetTrajectoryResponse.h>


namespace roboy_communication_middleware
{

struct SetTrajectory
{

typedef SetTrajectoryRequest Request;
typedef SetTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTrajectory
} // namespace roboy_communication_middleware


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_middleware::SetTrajectory > {
  static const char* value()
  {
    return "eaf3f910b01afc97910e678067741a78";
  }

  static const char* value(const ::roboy_communication_middleware::SetTrajectory&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_middleware::SetTrajectory > {
  static const char* value()
  {
    return "roboy_communication_middleware/SetTrajectory";
  }

  static const char* value(const ::roboy_communication_middleware::SetTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_middleware::SetTrajectoryRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_middleware::SetTrajectory > 
template<>
struct MD5Sum< ::roboy_communication_middleware::SetTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_middleware::SetTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::SetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_middleware::SetTrajectoryRequest> should match 
// service_traits::DataType< ::roboy_communication_middleware::SetTrajectory > 
template<>
struct DataType< ::roboy_communication_middleware::SetTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_middleware::SetTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::SetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_middleware::SetTrajectoryResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_middleware::SetTrajectory > 
template<>
struct MD5Sum< ::roboy_communication_middleware::SetTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_middleware::SetTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::SetTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_middleware::SetTrajectoryResponse> should match 
// service_traits::DataType< ::roboy_communication_middleware::SetTrajectory > 
template<>
struct DataType< ::roboy_communication_middleware::SetTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_middleware::SetTrajectory >::value();
  }
  static const char* value(const ::roboy_communication_middleware::SetTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_SETTRAJECTORY_H
