# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_communication_middleware/RoboyState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RoboyState(genpy.Message):
  _md5sum = "a564b9aee3211a3963e685c6ed14e5e1"
  _type = "roboy_communication_middleware/RoboyState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[] setPoint
float32[] actuatorPos
float32[] actuatorVel
float32[] tendonDisplacement
float32[] actuatorCurrent
"""
  __slots__ = ['setPoint','actuatorPos','actuatorVel','tendonDisplacement','actuatorCurrent']
  _slot_types = ['float32[]','float32[]','float32[]','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       setPoint,actuatorPos,actuatorVel,tendonDisplacement,actuatorCurrent

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RoboyState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.setPoint is None:
        self.setPoint = []
      if self.actuatorPos is None:
        self.actuatorPos = []
      if self.actuatorVel is None:
        self.actuatorVel = []
      if self.tendonDisplacement is None:
        self.tendonDisplacement = []
      if self.actuatorCurrent is None:
        self.actuatorCurrent = []
    else:
      self.setPoint = []
      self.actuatorPos = []
      self.actuatorVel = []
      self.tendonDisplacement = []
      self.actuatorCurrent = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.setPoint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.setPoint))
      length = len(self.actuatorPos)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.actuatorPos))
      length = len(self.actuatorVel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.actuatorVel))
      length = len(self.tendonDisplacement)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.tendonDisplacement))
      length = len(self.actuatorCurrent)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.actuatorCurrent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.setPoint = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorPos = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorVel = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.tendonDisplacement = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorCurrent = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.setPoint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.setPoint.tostring())
      length = len(self.actuatorPos)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.actuatorPos.tostring())
      length = len(self.actuatorVel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.actuatorVel.tostring())
      length = len(self.tendonDisplacement)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.tendonDisplacement.tostring())
      length = len(self.actuatorCurrent)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.actuatorCurrent.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.setPoint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorPos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorVel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.tendonDisplacement = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.actuatorCurrent = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
