// Generated by gencpp from file roboy_communication_control/ShowEmotion.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_CONTROL_MESSAGE_SHOWEMOTION_H
#define ROBOY_COMMUNICATION_CONTROL_MESSAGE_SHOWEMOTION_H

#include <ros/service_traits.h>


#include <roboy_communication_control/ShowEmotionRequest.h>
#include <roboy_communication_control/ShowEmotionResponse.h>


namespace roboy_communication_control
{

struct ShowEmotion
{

typedef ShowEmotionRequest Request;
typedef ShowEmotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShowEmotion
} // namespace roboy_communication_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_control::ShowEmotion > {
  static const char* value()
  {
    return "5a9d20fa9a1b468cec007dad13c554fc";
  }

  static const char* value(const ::roboy_communication_control::ShowEmotion&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_control::ShowEmotion > {
  static const char* value()
  {
    return "roboy_communication_control/ShowEmotion";
  }

  static const char* value(const ::roboy_communication_control::ShowEmotion&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_control::ShowEmotionRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_control::ShowEmotion > 
template<>
struct MD5Sum< ::roboy_communication_control::ShowEmotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_control::ShowEmotion >::value();
  }
  static const char* value(const ::roboy_communication_control::ShowEmotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_control::ShowEmotionRequest> should match 
// service_traits::DataType< ::roboy_communication_control::ShowEmotion > 
template<>
struct DataType< ::roboy_communication_control::ShowEmotionRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_control::ShowEmotion >::value();
  }
  static const char* value(const ::roboy_communication_control::ShowEmotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_control::ShowEmotionResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_control::ShowEmotion > 
template<>
struct MD5Sum< ::roboy_communication_control::ShowEmotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_control::ShowEmotion >::value();
  }
  static const char* value(const ::roboy_communication_control::ShowEmotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_control::ShowEmotionResponse> should match 
// service_traits::DataType< ::roboy_communication_control::ShowEmotion > 
template<>
struct DataType< ::roboy_communication_control::ShowEmotionResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_control::ShowEmotion >::value();
  }
  static const char* value(const ::roboy_communication_control::ShowEmotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_CONTROL_MESSAGE_SHOWEMOTION_H
