controller_list:
  - name: fake_thumb_limb3_controller
    joints:
      - palm_thumb
      - joint0_thumb
      - joint1_thumb
      - joint2_thumb
  - name: fake_index_limb3_controller
    joints:
      - palm_index
      - joint0_index
      - joint1_index
      - joint2_index
  - name: fake_middle_limb3_controller
    joints:
      - palm_middle
      - joint0_middle
      - joint1_middle
      - joint2_middle
  - name: fake_ring_limb3_controller
    joints:
      - palm_ring
      - joint0_ring
      - joint1_ring
      - joint2_ring
  - name: fake_little_limb3_controller
    joints:
      - palm_little
      - joint0_little
      - joint1_little
      - joint2_little