hand_left:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin #roboy_xylophone_left_arm_hand_left_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
