; Auto-generated. Do not edit!


(cl:in-package roboy_communication_control-msg)


;//! \htmlinclude PerformMovementsFeedback.msg.html

(cl:defclass <PerformMovementsFeedback> (roslisp-msg-protocol:ros-message)
  ((todo_movements
    :reader todo_movements
    :initarg :todo_movements
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass PerformMovementsFeedback (<PerformMovementsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PerformMovementsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PerformMovementsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roboy_communication_control-msg:<PerformMovementsFeedback> is deprecated: use roboy_communication_control-msg:PerformMovementsFeedback instead.")))

(cl:ensure-generic-function 'todo_movements-val :lambda-list '(m))
(cl:defmethod todo_movements-val ((m <PerformMovementsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roboy_communication_control-msg:todo_movements-val is deprecated.  Use roboy_communication_control-msg:todo_movements instead.")
  (todo_movements m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PerformMovementsFeedback>) ostream)
  "Serializes a message object of type '<PerformMovementsFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'todo_movements))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'todo_movements))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PerformMovementsFeedback>) istream)
  "Deserializes a message object of type '<PerformMovementsFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'todo_movements) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'todo_movements)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PerformMovementsFeedback>)))
  "Returns string type for a message object of type '<PerformMovementsFeedback>"
  "roboy_communication_control/PerformMovementsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PerformMovementsFeedback)))
  "Returns string type for a message object of type 'PerformMovementsFeedback"
  "roboy_communication_control/PerformMovementsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PerformMovementsFeedback>)))
  "Returns md5sum for a message object of type '<PerformMovementsFeedback>"
  "88978ba98eef12f309b88c02d13d2ba2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PerformMovementsFeedback)))
  "Returns md5sum for a message object of type 'PerformMovementsFeedback"
  "88978ba98eef12f309b88c02d13d2ba2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PerformMovementsFeedback>)))
  "Returns full string definition for message of type '<PerformMovementsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string[] todo_movements~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PerformMovementsFeedback)))
  "Returns full string definition for message of type 'PerformMovementsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string[] todo_movements~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PerformMovementsFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'todo_movements) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PerformMovementsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PerformMovementsFeedback
    (cl:cons ':todo_movements (todo_movements msg))
))
