(cl:in-package roboy_communication_middleware-msg)
(cl:export '(ID-VAL
          ID
          RECORDTIME-VAL
          RECORDTIME
          SAMPLINGTIME-VAL
          SAMPLINGTIME
          CONTROL_MODE-VAL
          CONTROL_MODE
          MOTOR0-VAL
          MOTOR0
          MOTOR1-VAL
          MOTOR1
          MOTOR2-VAL
          MOTOR2
          MOTOR3-VAL
          MOTOR3
          MOTOR4-VAL
          MOTOR4
          MOTOR5-VAL
          MOTOR5
          MOTOR6-VAL
          MOTOR6
          MOTOR7-VAL
          MOTOR7
          MOTOR8-VAL
          MOTOR8
          MOTOR9-VAL
          MOTOR9
          MOTOR10-VAL
          MOTOR10
          MOTOR11-VAL
          MOTOR11
          MOTOR12-VAL
          MOTOR12
          MOTOR13-VAL
          MOTOR13
))