(cl:in-package roboy_communication_middleware-msg)
(cl:export '(ID-VAL
          ID
          MOTORS-VAL
          MOTORS
          CONTROL_MODE-VAL
          CONTROL_MODE
          OUTPUTPOSMAX-VAL
          OUTPUTPOSMAX
          OUTPUTNEGMAX-VAL
          OUTPUTNEGMAX
          SPPOSMAX-VAL
          SPPOSMAX
          SPNEGMAX-VAL
          SPNEGMAX
          KP-VAL
          KP
          KI-VAL
          KI
          KD-VAL
          KD
          FORWARDGAIN-VAL
          FORWARDGAIN
          DEADBAND-VAL
          DEADBAND
          INTEGRALPOSMAX-VAL
          INTEGRALPOSMAX
          INTEGRALNEGMAX-VAL
          INTEGRALNEGMAX
))