(cl:in-package roboy_communication_middleware-msg)
(cl:export '(LIGHTHOUSE-VAL
          LIGHTHOUSE
          FW_VERSION-VAL
          FW_VERSION
          ID-VAL
          ID
          FCAL_0_PHASE-VAL
          FCAL_0_PHASE
          FCAL_1_PHASE-VAL
          FCAL_1_PHASE
          FCAL_0_TILT-VAL
          FCAL_0_TILT
          FCAL_1_TILT-VAL
          FCAL_1_TILT
          UNLOCK_COUNT-VAL
          UNLOCK_COUNT
          HW_VERSION-VAL
          HW_VERSION
          FCAL_0_CURVE-VAL
          FCAL_0_CURVE
          FCAL_1_CURVE-VAL
          FCAL_1_CURVE
          ACCEL_DIR_X-VAL
          ACCEL_DIR_X
          ACCEL_DIR_Y-VAL
          ACCEL_DIR_Y
          ACCEL_DIR_Z-VAL
          ACCEL_DIR_Z
          FCAL_0_GIBPHASE-VAL
          FCAL_0_GIBPHASE
          FCAL_1_GIBPHASE-VAL
          FCAL_1_GIBPHASE
          FCAL_0_GIBMAG-VAL
          FCAL_0_GIBMAG
          FCAL_1_GIBMAG-VAL
          FCAL_1_GIBMAG
          MODE-VAL
          MODE
          FAULTS-VAL
          FAULTS
          CRC32-VAL
          CRC32
))